
version: "3.9"

services:
  mongo-query-generator:
    build: .
    ports:
      - "3001:3001"
      - "5173:5173"
    volumes:
      - ./server/src/collections.json:/app/server/src/collections.json
    environment:
      - NODE_ENV=production
